/*
 * ACTION TYPES
 */

export const ActionTypes = {
  INIT_APP_REQUEST: 'INIT_APP_REQUEST',
  INIT_APP_DONE: 'INIT_APP_DONE',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_DONE: 'LOGIN_DONE',
  SET_FORGOT_PASSWORD_URL: 'SET_FORGOT_PASSWORD_URL',
  SET_SIGNUP_URL: 'SET_SIGNUP_URL',
  SET_OS: 'SET_OS',
  SET_PAGE: 'SET_PAGE',
  SET_VERSION: 'SET_VERSION',
  TOGGLE_DROPDOWN: 'TOGGLE_DROPDOWN'
}

/*
 * OTHER CONSTANTS
 */

export const Pages = {
  LOADING: 'LOADING',
  LOGIN: 'LOGIN',
  MAIN: 'MAIN',
  SETTINGS: 'SETTINGS',
  OUT_OF_DATE: 'OUT_OF_DATE'
}

export const Paths = {
  FORGOT_PASSWORD: '#/request-password-from-uploader',
  SIGNUP: '#/signup'
}