/*
 * == BSD2 LICENSE ==
 * Copyright (c) 2015, Tidepool Project
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the associated License, which is identical to the BSD 2-Clause
 * License as published by the Open Source Initiative at opensource.org.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the License for more details.
 *
 * You should have received a copy of the License along with this program; if
 * not, you can obtain one from Tidepool Project at tidepool.org.
 * == BSD2 LICENSE ==
 */

import _ from 'lodash';

const working = {
  inProgress: false,
  notification: null,
  completed: null,
};

const initialState = {
  passwordResetConfirmed: false,
  showingWelcomeMessage: null,
  showingDonateBanner: null,
  showingDexcomConnectBanner: null,
  showingShareDataBanner: null,
  seenShareDataBannerMax: false,
  showingUpdateTypeBanner: null,
  showingUploaderBanner: null,
  signupKey: null,
  isLoggedIn: false,
  sentEmailVerification: false,
  resentEmailVerification: false,
  loggedInUserId: null,
  targetUserId: null,
  currentPatientInViewId: null,
  membersOfTargetCareTeam: [],
  membershipInOtherCareTeams: [],
  permissionsOfMembersInTargetCareTeam: {},
  membershipPermissionsInOtherCareTeams: {},
  allUsers: {},
  pdf: {},
  data: {
    data: {
      aggregationsByDate: {},
      combined: [],
      current: {},
      next: {},
      prev: {},
    },
    timePrefs: {},
    bgPrefs: {},
    metaData: {},
    query: {},
    fetchedUntil: null,
    cacheUntil: null,
  },
  pendingReceivedInvites: [],
  pendingSentInvites: [],
  prescriptions: [],
  devices: {},
  messageThread: null,
  working: {
    acceptingReceivedInvite: Object.assign({}, working),
    acceptingTerms: Object.assign({}, working),
    cancellingSentInvite: Object.assign({}, working),
    confirmingPasswordReset: Object.assign({}, working),
    confirmingSignup: Object.assign({}, working),
    connectingDataSource: Object.assign({}, working),
    disconnectingDataSource: Object.assign({}, working),
    settingUpDataStorage: Object.assign({}, working),
    rejectingReceivedInvite: Object.assign({}, working),
    fetchingDataDonationAccounts: Object.assign({}, working),
    fetchingDataSources: Object.assign({}, working),
    fetchingServerTime: Object.assign({}, working),
    fetchingPrescriptions: Object.assign({}, working),
    creatingPrescription: Object.assign({}, working),
    creatingPrescriptionRevision: Object.assign({}, working),
    deletingPrescription: Object.assign({}, working),
    fetchingDevices: Object.assign({}, working),
    fetchingMessageThread: Object.assign({}, working),
    creatingMessageThread: Object.assign({}, working),
    editingMessageThread: Object.assign({}, working),
    fetchingPatient: Object.assign({}, working),
    fetchingPatientData: Object.assign({}, working),
    fetchingAssociatedAccounts: Object.assign({}, working),
    fetchingPendingReceivedInvites: Object.assign({}, working),
    fetchingPendingSentInvites: Object.assign({}, working),
    fetchingUser: Object.assign({}, working),
    generatingPDF: Object.assign({}, working),
    addingData: Object.assign({}, working),
    removingData: Object.assign({}, working),
    updatingDatum: Object.assign({}, working),
    queryingData: Object.assign({}, working),
    loggingIn: Object.assign({}, working),
    loggingOut: Object.assign({}, working),
    removingMembershipInOtherCareTeam: Object.assign({}, working),
    removingMemberFromTargetCareTeam: Object.assign({}, working),
    requestingPasswordReset: Object.assign({}, working),
    resendingEmailVerification: Object.assign({}, working),
    sendingInvite: Object.assign({}, working),
    settingMemberPermissions: Object.assign({}, working),
    updatingDataDonationAccounts: Object.assign({}, working),
    updatingPatient: Object.assign({}, working),
    updatingPatientBgUnits: Object.assign({}, working),
    updatingUser: Object.assign({}, working),
    verifyingCustodial: Object.assign({}, working),
    signingUp: Object.assign({}, working),
    fetchingClinics: Object.assign({}, working),
    creatingClinic: Object.assign({}, working),
    fetchingClinic: Object.assign({}, working),
    updatingClinic: Object.assign({}, working),
    fetchingCliniciansFromClinic: Object.assign({}, working),
    fetchingClinician: Object.assign({}, working),
    updatingClinician: Object.assign({}, working),
    deletingClinicianFromClinic: Object.assign({}, working),
    fetchingPatientsForClinic: Object.assign({}, working),
    creatingCustodialAccount: Object.assign({}, working),
    fetchingPatientFromClinic: Object.assign({}, working),
    updatingClinicPatient: Object.assign({}, working),
    sendingClinicianInvite: Object.assign({}, working),
    resendingClinicianInvite: Object.assign({}, working),
    deletingClinicianInvite: Object.assign({}, working),
    fetchingPatientInvites: Object.assign({}, working),
    acceptingPatientInvitation: Object.assign({}, working),
    updatingPatientPermissions: Object.assign({}, working),
    fetchingClinicsForPatient: Object.assign({}, working),
    fetchingClinicianInvites: Object.assign({}, working),
    acceptingClinicianInvite: Object.assign({}, working),
    dismissingClinicianInvite: Object.assign({}, working),
    fetchingClinicsForClinician: Object.assign({}, working),
  },
  notification: null,
  timePrefs: {
    timezoneAware: false,
    timezoneName: null
  },
  dataDonationAccounts: [],
  dataSources: [],
  authorizedDataSource: null,
  clinics: {},
  selectedClinicId: null,
  pendingReceivedClinicianInvites: [],
  dropdown: false,
  os: null,
  unsupported: true,
  blipUrls: {},
  checkingVersion: false,
  fetchingUserInfo: false,
  initializingApp: true,
  uploading: false,
  checkingElectronUpdate: false,
  checkingDriverUpdate: false,
  electronUpdateManualChecked: null,
  electronUpdateAvailableDismissed: null,
  electronUpdateAvailable: null,
  electronUpdateDownloaded: null,
  driverUpdateAvailable: null,
  driverUpdateAvailableDismissed: null,
  driverUpdateShellOpts: null,
  driverUpdateComplete: null,
  showingDeviceTimePrompt: null,
  isTimezoneFocused: false,
  showingAdHocPairingDialog: false,
};

export default initialState;
